# Generated by Django 2.1.3 on 2019-01-08 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.RenameField(
            model_name='backup',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='picture',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='backup',
            name='product',
        ),
        migrations.AddField(
            model_name='backup',
            name='search_product',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='backup',
            name='subs_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='front_picture',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_picture',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
