# Generated by Django 2.1.3 on 2018-12-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='picture',
            new_name='front_picture',
        ),
    ]
