# Generated by Django 2.1.3 on 2019-01-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190108_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='search_product',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
