# Generated by Django 2.1.3 on 2019-01-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190102_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutrition_picture',
            field=models.URLField(),
        ),
    ]
