# Generated by Django 2.1.3 on 2019-01-10 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20190110_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_search', to='app.Product')),
                ('subs_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_substitute', to='app.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
