# Generated by Django 2.1.3 on 2019-01-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_backup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='search_product',
        ),
        migrations.RemoveField(
            model_name='backup',
            name='subs_product',
        ),
        migrations.RemoveField(
            model_name='backup',
            name='user',
        ),
        migrations.DeleteModel(
            name='Backup',
        ),
    ]
