# Generated by Django 2.1.3 on 2019-01-10 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('save', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='search_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='backup_search', to='app.Product'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='subs_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='backup_substitute', to='app.Product'),
        ),
    ]
