# Generated by Django 2.1.3 on 2019-01-10 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('app', '0007_auto_20190110_1333'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('save', '0003_auto_20190110_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_product',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_search',
                                   to='app.Product')),
                ('subs_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='backup_substitute', to='app.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
